# Generated by Django 5.2.3 on 2025-06-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="User's full name.", max_length=255)),
                ('email', models.EmailField(help_text="User's email address.", max_length=254, unique=True)),
                ('mobile_number', models.CharField(help_text="User's mobile number (e.g., +919876543210).", max_length=15, unique=True)),
                ('password', models.CharField(help_text='Hashed user password.', max_length=128)),
                ('terms_accepted', models.BooleanField(default=False, help_text='Indicates if user agreed to terms and conditions.')),
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
                'db_table': 'app_user',
            },
        ),
    ]
