# Generated by Django 5.2.3 on 2025-06-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityDesk', '0002_communitypost_comment_follow_poll_polloption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
